// Generated by CoffeeScript 1.7.1
var fs, ssh2;

ssh2 = require('ssh2');

fs = require('fs');

module.exports = function(options, callback) {
  var connect, match, privateKeyPath, retry, st;
  if (options instanceof ssh2) {
    return callback(null, options);
  }
  if (options.username == null) {
    options.username = process.env['USER'];
  }
  if (options.retry == null) {
    options.retry = 1;
  }
  if (!options.password && !options.privateKey) {
    if (options.privateKeyPath == null) {
      options.privateKeyPath = '~/.ssh/id_rsa';
    }
    if (options.privateKeyPath && (match = /~(\/.*)/.exec(options.privateKeyPath))) {
      options.privateKeyPath = process.env.HOME + match[1];
    }
  } else {
    options.privateKeyPath = null;
  }
  privateKeyPath = function() {
    if (!options.privateKeyPath) {
      return connect();
    }
    return fs.readFile(options.privateKeyPath, 'ascii', function(err, privateKey) {
      options.privateKey = privateKey;
      return connect();
    });
  };
  retry = options.retry;
  st = Date.now();
  connect = function() {
    var connection;
    if (retry !== true && retry > 0) {
      retry--;
    }
    connection = new ssh2();
    connection.on('error', function(err) {
      connection.end();
      if (retry === true || retry > 0) {
        return setTimeout(connect, 2000);
      } else {
        return callback(err);
      }
    });
    connection.on('ready', function() {
      return callback(null, connection);
    });
    return connection.connect(options);
  };
  return privateKeyPath();
};
